version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: task-manager-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: task-manager-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb

volumes:
  mongo-data:
