name: Auto Deploy Task Manager API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH & Deploy Safely
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 3.215.43.139
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "==== CONNECTED TO EC2 ===="

            cd ~/task-manager-api || exit 1

            echo "==== PULLING LATEST CODE ===="
            git pull origin main || exit 1

            echo "==== STOPPING OLD CONTAINERS ===="
            docker-compose down || true

            echo "==== BUILDING & STARTING NEW CONTAINERS ===="
            docker-compose up -d --build || exit 1

            echo "==== CLEANING UNUSED IMAGES ===="
            docker image prune -f || true

            echo "==== DEPLOYMENT SUCCESSFUL 🚀 ===="
